services:
  viper:
    build: .
    image: viper-image
    ports:
      - "1073:80"
    container_name: viper-container
    volumes:
      - .:/usr/local/apache2/htdocs

# docker compose up
# Visit: http://localhost:1073/
# ctrl-c to stop it
